# Generated by Django 3.2.5 on 2021-11-14 22:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='landImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='squareImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tallImage',
        ),
        migrations.AddField(
            model_name='image',
            name='imagemdois',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem2.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img2'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagemtres',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem3.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img3'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagemum',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem1.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img1'),
        ),
    ]
