# Generated by Django 3.2.5 on 2021-11-15 14:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211114_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imagemum',
            new_name='imagem1',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imagemdois',
            new_name='imagem2',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imagemtres',
            new_name='imagem3',
        ),
        migrations.AddField(
            model_name='image',
            name='imagem10',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem10.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img10'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem11',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem11.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img11'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem12',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem12.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img12'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem4',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem4.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img4'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem5',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem5.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img5'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem6',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem6.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img6'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem7',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem7.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img7'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem8',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem8.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img8'),
        ),
        migrations.AddField(
            model_name='image',
            name='imagem9',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem9.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img9'),
        ),
    ]
