# Generated by Django 3.2.5 on 2021-11-15 14:52

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20211115_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('altText', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=300, null=True)),
                ('imagem1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem1.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img1')),
                ('imagem2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem2.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img2')),
                ('imagem3', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem3.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img3')),
                ('imagem4', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem4.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img4')),
                ('imagem5', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem5.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img5')),
                ('imagem6', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem6.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img6')),
                ('imagem7', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem7.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img7')),
                ('imagem8', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem8.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img8')),
                ('imagem9', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem9.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img9')),
                ('imagem10', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem10.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img10')),
                ('imagem11', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem11.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img11')),
                ('imagem12', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_imagem12.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='img12')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Paciente',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='fotos',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.paciente'),
        ),
    ]
