# Generated by Django 3.2.5 on 2021-11-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20211115_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Paciente',
        ),
    ]
